name: Deploy to GCP

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
      working-directory: TechFusor/techfusor-app  # Adjust if needed

    - name: Build React app
      run: npm run build
      working-directory: TechFusor/techfusor-app

    - name: Deploy to GCP
      run: |
        ssh -i ${{ secrets.GCP_PRIVATE_KEY }} ${{ secrets.GCP_USERNAME }}@${{ secrets.GCP_HOST }} 'bash -s' << 'EOF'
          cd /home/deploy/TechFusor/techfusor-app/
          sudo rm -rf *  # Remove existing files
          sudo cp -r $HOME/TechFusor/techfusor-app/build/* .
          sudo systemctl restart nginx
        EOF
