name: Deploy to GCP

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
      working-directory: techfusor-app  # Adjust if needed

    - name: Build React app
      run: npm run build
      working-directory: techfusor-app

    - name: Deploy to GCP
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.GCP_HOST }}
        REMOTE_USER: ${{ secrets.GCP_USERNAME }}
        SCRIPT_BEFORE: |
           cd /home/deploy/TechFusor/techfusor-app/
           sudo rm -rf *  # Remove existing files
           sudo cp -r $GITHUB_WORKSPACE/TechFusor/techfusor-app/* .
           sudo systemctl restart nginx
