name: Deploy to GCP

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
      working-directory: techfusor-app  # Adjust if needed

    - name: Build React app
      run: npm run build
      working-directory: techfusor-app

    - name: Deploy to GCP
      run: |
        echo "${PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem

        # Add host key to known_hosts
        ssh-keyscan -H 34.125.144.12 >> ~/.ssh/known_hosts

        # Run the scp command
        scp -i private_key.pem -r $GITHUB_WORKSPACE/TechFusor/techfusor-app/* deploy@34.125.144.12:/home/deploy/TechFusor
      env:
        PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
